name: Calendar
main: com.github.tonedahonda.calendar.backend.Main
version: ${project.version}
author: Joshua Wirtz
authors: []
website: https://www.spigotmc.org/resources/29122/
softdepend: [PlaceholderAPI]

commands:
 calendar:
  usage: /calendar
  description: Calendar function.
 appointment:
  usage: |
         /appointment [add/remove] [Visibillity] [Date] [Name] [Header] [Description]
         /appointment reminder - toggle appointment reminder
  description: Calendar appointment function.
  
permissions:
  calendar.*:
    description: Gives access to all Calendar commands.
    children:
      calendar.open: true
      calendar.reload: true
      calendar.appointment.*: true
  calendar.appointment.*:
   description: Gives access to all Calendar appointment commands.
   children:
     calendar.appointment.add: true
     calendar.appointment.remove: true
     calendar.appointment.restore: true
     calendar.appointment.reminder: true
  calendar.appointment.add:
    description: Gives access to all Calendar add appointment commands.
    children:
      calendar.appointment.add.private: true
      calendar.appointment.add.public: true
  calendar.appointment.remove:
    description: Gives access to all Calendar remove appointment commands.
    children:
      calendar.appointment.remove.private: true
      calendar.appointment.remove.public: true
  calendar.appointment.restore:
    description: Gives access to all Calendar restore appointment commands.
    children:
      calendar.appointment.restore.private: true
      calendar.appointment.restore.public: true