name: Calendar
main: calendar.backend.main.main
version: 1.0
author: Joshua Wirtz
website: https://www.spigotmc.org/resources/25146/

commands:
 calendar:
  usage: /calendar
  description: TheTime calendar function.