#       Calendar
#  Author: Joshua Wirtz
# 
#     IDs for block color/type ids you can find here: http://minecraft.gamepedia.com/Data_values
#     Formatting codes can be used with &[ForamttingCode], here you will find a list with all formatting codes: http://minecraft.gamepedia.com/Formatting_codes
#     
#     Placeholders:
#       - %date_second%    - displays the current second.
#       - %date_minute%    - displays the current minute.
#       - %date_hour%      - displays the current hour.
#       - %date_day%       - displays the day of the item.
#       - %date_week%      - displays the week of the item.
#       - %date_month%     - displays the current month.
#       - %date_year%      - displays the current year.
#     
#       - %date_day_name%   - displays the name of the day.
#       - %date_month_name% - displays the current month name.
# 
#       - %appointment_name%        - displays the name of the appointment.
#       - %appointment_header%      - displays the header of the appointment.
#       - %appointment_description% - Comming soon!
#  
#       - %appointment_date_second%    - displays the second of the appointment.
#       - %appointment_date_minute%    - displays the minute of the appointment.
#       - %appointment_date_hour%      - displays the hour of the appointment.
#       - %appointment_date_hour_am_pm%- displays the hour of am pm of the appointment.
#       - %appointment_date_day%       - displays the day of the appointment.
#       - %appointment_date_week%      - displays the week of the appointment.
#       - %appointment_date_month%     - displays the month of the appointment.
#       - %appointment_date_year%      - displays the year of the appointment.
#     
#       - %appointment_date_day_name%   - displays the name of the appointment's day.
#       - %appointment_date_month_name% - displays the month name of the appointment's month.
#  
#    A list of all avilable block materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html 
#  
# Info:
#  inventory:
#   'size:' will be the buffer size of the inventory.
#   'toggle:' if you set this to false the item will not be displayed.
#   'amount:' The amount can also be a placeholder.
#   'lore:' if you remove this parameter there will be no lore displayed. You can also add it again.(Don't leave it there with no value it will cause errors)
#  reminder:
#   'toggle:' if you set this to false you will not get reminded.
#   'message:' this will be displayed when you get reminded.
#   'startAt:' value in minutes how long before the appointment the reminder will start.
#   'repeatAfter:' value in ticks how much time is between the remind messages.
#  
prefixes:
  header: '&4█ &8'
  description: '&2█ &7'
reminder:
  toggle: true
  message: 'Appointment %appointment_header% takes place at %appointment_date_hour%:%appointment_date_minute%!'
  startTime: 0:5:0
  waitTime: 0:1:0
inventorys:
  appointmentManager:
    title: 'Appointments - %date_day%. %date_month_name%'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name: '&rBack'
        material: BARRIER
        id: 0
        amount: 1
      addAppointment:
        toggle: true
        slot: 7
        name: '&rAdd appointment'
        material: STAINED_CLAY
        id: 13
        amount: 1
      restoreAppointment:
        toggle: true
        slot: 0
        name: '&r&8Trash'
        material: CAULDRON_ITEM
        id: 0
        amount: 1
      publicAppointments:
        toggle: true
        name: '&râ–Œ %appointment_name%'
        material: STAINED_GLASS_PANE
        id: 3
        amount: 1
        lore:
        - '&7█ %appointment_date_hour%:%appointment_date_minute%:%appointment_date_second%'
      privateAppointments:
        toggle: true
        name: '&r█ %appointment_name%'
        material: STAINED_GLASS_PANE
        id: 13
        amount: 1
        lore:
        - '&7█ %appointment_date_hour%:%appointment_date_minute%:%appointment_date_second%'
  addAppointment:
    title: '&rAdd appointment on %date_day%. %date_month_name%'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name: '&rBack'
        material: BARRIER
        id: 0
        amount: 1
      setStatus:
        toggle: true
        slot: 0
        name: '&r&lVisibility'
        material: STAINED_GLASS_PANE
        id: 3
        amount: 1
        lore:
        - '&r&7Visibility: &r%appointment_status%'
      setTime:
        toggle: true
        slot: 1
        name: '&r&lTime'
        material: WATCH
        id: 0
        amount: 1
        lore:
        - '&r&o&8Sets the time of the appointment. (hh:mm:ss)'
        - '&r&7Time: &r%appointment_date_hour%:%appointment_date_minute%:%appointment_date_second%'
      setName:
        toggle: true
        slot: 3
        name: '&r&lName'
        material: STAINED_CLAY
        id: 13
        amount: 1
        lore:
        - '&r&o&8Sets the name of the appointment.'
        - '&r&7Name: &r%appointment_name%'
      setHeader:
        toggle: true
        slot: 4
        name: '&r&lHeader'
        material: STAINED_CLAY
        id: 2
        amount: 1
        lore:
        - '&r&o&8Sets the header of the appointment.'
        - '&r&7Header: &r%appointment_header%'
      setDescription:
        toggle: true
        slot: 5
        name: '&r&lDescription'
        material: STAINED_CLAY
        id: 5
        amount: 1
        lore:
        - '&r&o&8Sets the description of the appointment'
        - '&r&7Description: &r%appointment_description%'
      confirm:
        toggle: true
        slot: 7
        name: '&r&2&lConfirm'
        material: EMERALD_BLOCK
        id: 0
        amount: 1
  removeAppointment:
    title: '&4&lREMOVE: &r"%appointment_name%"'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name:  '&rBack'
        material: BARRIER
        id: 0
        amount: 1
      confirm:
        toggle: true
        slot: 4
        name: '&r&2&lConfirm'
        material: EMERALD_BLOCK
        id: 0
        amount: 1
        lore:
        - '&rPress &2&lConfirm&r to delete this appointment.'
  appointmentTrash:
    title: 'Appointment Trash'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name:  '&rBack'
        material: BARRIER
        id: 0
        amount: 1
      deletedAppointments:
        toggle: true
        slot: 4
        name: '&r█ %appointment_name%'
        material: PAPER
        id: 0
        amount: 1
        lore:
        - '&r&4█&r %appointment_header%'
        - '&r&2█&r %appointment_description%'