#       Calendar
#  Author: Joshua Wirtz
# 
#     IDs for block color/type ids you can find here: http://minecraft.gamepedia.com/Data_values
#     Formatting codes can be used with &[ForamttingCode], here you will find a list with all formatting codes: http://minecraft.gamepedia.com/Formatting_codes
#     
#     Placeholders:
#       - %date_second%    - displays the current second.
#       - %date_minute%    - displays the current minute.
#       - %date_hour%      - displays the current hour.
#       - %date_day%       - displays the day of the item.
#       - %date_week%      - displays the week of the item.
#       - %date_month%     - displays the current month.
#       - %date_year%      - displays the current year.
#     
#       - %date_day_name%   - displays the name of the day.
#       - %date_month_name% - displays the current month name.
# 
#       - %appointment_name%        - displays the name of the appointment.
#       - %appointment_header%      - displays the header of the appointment.
#       - %appointment_description% - Comming soon!
#  
#       - %appointment_date_second%    - displays the second of the appointment.
#       - %appointment_date_minute%    - displays the minute of the appointment.
#       - %appointment_date_hour%      - displays the hour of the appointment.
#       - %appointment_date_day%       - displays the day of the appointment.
#       - %appointment_date_week%      - displays the week of the appointment.
#       - %appointment_date_month%     - displays the month of the appointment.
#       - %appointment_date_year%      - displays the year of the appointment.
#     
#       - %appointment_date_day_name%   - displays the name of the appointment's day.
#       - %appointment_date_month_name% - displays the month name of the appointment's month.
#  
#    A list of all avilable block materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html 
#  
# Info:
#   'size:' will be the buffer size of the inventory.
#   'toggle:' if you set this to false the item will not be displayed.
#   'amount:' The amount can also be a placeholder.
#   'lore:' if you remove this parameter there will be no lore displayed. You can also add it again.(Don't leave it there with no value it will cause errors)
prefixes:
  header: '&4▌ &8'
  description: '&2▌ &7'
inventorys:
  appointmentManager:
    title: 'Appointments - %date_day%. %date_month_name%'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name: Back to calendar
        material: BARRIER
        id: 0
        amount: 1
      publicAppointments:
        toggle: true
        name: '&r▌ %appointment_name%'
        material: STAINED_GLASS_PANE
        id: 3
        amount: 1
      privateAppointments:
        toggle: true
        name: '&r▌ %appointment_name%'
        material: STAINED_GLASS_PANE
        id: 13
        amount: 1
  addAppointment:
    title: 'Add appointment on %date_day%. %date_monthName%'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name: Back to calendar
        material: BARRIER
        id: 0
        amount: 1
      setStatus:
        toggle: true
        slot: 0
        name: 'Publicity status'
        material: GLASS
        id: 0
        amount: 1
        lore:
        - '&rCan be public or private'
      setName:
        toggle: true
        slot: 1
        name: 'Name'
        material: GLASS
        id: 0
        amount: 1
        lore:
        - 'Sets the name of the appointment.'
        - 'Will be used to store it.'
      setHeader:
        toggle: true
        slot: 2
        name: 'Header'
        material: BARRIER
        id: 0
        amount: 1
        lore:
        - 'Sets the header of the appointment'
        - '&[ColorCode] - Colors'
      setDescription:
        toggle: true
        slot: 3
        name: 'Description'
        material: GLASS
        id: 0
        amount: 1
        lore:
        - 'Sets the description of the appointment'
        - '&[ColorCode] - Colors'
        - '%n           - Next line'
  removeAppointment:
    title: '&4&lREMOVE: &r"%appointment_name%"'
    size: 9
    items:
      backToCalendar:
        toggle: true
        slot: 8
        name:  'Back to calendar'
        material: BARRIER
        id: 0
        amount: 1
      confirm:
        toggle: true
        slot: 4
        name: '&r&2&lConfirm'
        material: EMERALD_BLOCK
        id: 0
        amount: 1
        lore:
        - '&rPress &2&lConfirm&r to delete this appointment.'