#       Calendar
#  Author: Joshua Wirtz
# 
#     IDs for block color/type ids you can find here: http://minecraft.gamepedia.com/Data_values
#     Formatting codes can be used with &[ForamttingCode], here you will find a list with all formatting codes: http://minecraft.gamepedia.com/Formatting_codes
#     
#     Placeholders:
#       - %second%    - displays the current second.
#       - %minute%    - displays the current minute.
#       - %hour%      - displays the current hour.
#       - %day%       - displays the day of the item.
#       - %week%      - displays the week of the item.
#       - %month%     - displays the current month.
#       - %year%      - displays the current year.
#     
#       - %dayName%   - displays the name of the day.
#       - %monthName% - displays the current month name.
# 
#    A list of all avilable block materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html 
#  
# Info:
#   'size:' will be the minimum size of the inventory.
#   'toggle:' if you set this to false the item will not be displayed.
#   'amount:' The amount can also be a placeholder.
#   'lore:' if you remove this parameter there will be no lore displayed. You can also add it again.(Don't leave it there with no value it will cause errors)
# 
# TimeZone:
# To find your time zone you can use this list: https://garygregory.wordpress.com/2013/06/18/what-are-the-java-timezone-ids/
# 
# Local:
# To find your locale use this list: http://www.oracle.com/technetwork/java/javase/javase7locales-334809.html
# 
timeZone: 458
locale: 'en_GB'
title: '%dayName%, %day%. %monthName% %year%'
size: 9
items:
  today:
    name: '&2%day%'
    material: STAINED_GLASS_PANE
    id: 5
    amount: '%day%'
    lore:
    - '&r%dayName%'
  day:
    name: '&2%day%'
    material: STAINED_GLASS_PANE
    id: 0
    amount: '%day%'
    lore:
    - '&r%dayName%'
  week:
    name: '&3Week %week%'
    material: STAINED_GLASS_PANE
    id: 7
    amount: '%week%'
  appointment:
    lore:
      prefix:
        header: ' &4▌ &7'
        description: ' &2▌ &8'
    enchantment:
      toggle: true
      type: OXYGEN
      strength: 0
      ignoreMax: true