#       Calendar
#  Author: Joshua Wirtz
# 
# Formatting codes can be used with &[ForamttingCode], here you will find a list with all formatting codes: http://minecraft.gamepedia.com/Formatting_codes
# 
# Permissions:
#   calendar.open  - Gives permissions to open the calendar
Errors:
  unknownCommand: '&oUnknown command! Try &r/calendar'
  notPlayer: 'This command is not executable in the consol!'
  noPermissions: '&oYou do not have permissions to do that!'
  appointmentAlreadyExsists: '&oThis appointment already exsists!'
  appointmentNotExsists: '&oThis appointment does not exsist!'
Notifications:
  configsReloaded: '&oConfigs have been reloaded!'
  appointmentAdded: '&oAppointment added!'
  appointmentRemoved: '&oAppointment removed!'
  appointmentRestored: '&oAppointment restored!'
  